### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by bob-tm** [igor-podpalchenko/ha-devi-mqtt#4]
```
Discovery cycle started
Enter OTP: 3495849
00:14:06.928 [main] INFO  i.h.b.d.i.GridConnectionKeeper - Last user is gone, disconnecting from Danfoss grid
00:14:06.940 [main] INFO  i.h.b.d.i.GridConnectionKeeper - Grid connection closed
00:14:06.951 [main] INFO  i.h.d.mqtt.service.DiscoveryService - Received DeviSmart thing: 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67 С/у
00:14:06.953 [main] INFO  i.h.d.mqtt.service.DiscoveryService - Received DeviSmart thing: 1dbd5d7d402ee334a8792b5bed13f10e8d6237a4f44d9afcac965ce3169f1b12 Баня
00:14:06.953 [main] INFO  i.h.d.mqtt.service.DiscoveryService - Received DeviSmart thing: 58ace24aa181f8252c8a6204e1a34bb7b13ccc998b8adb4693e075bab7b9696f Гараж
Discovery cycle ended
Querying thermostat serial numbers started
Connecting to peer: 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67
00:14:07.416 [pool-1-thread-1] INFO  i.h.b.d.i.GridConnectionKeeper - Successfully connected to Danfoss grid
00:14:07.417 [pool-1-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connecting to peer 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67
00:14:09.524 [pool-1-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connection established
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_serial_number, value: 10006152
00:14:09.528 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Last user is gone, disconnecting from Danfoss grid
00:14:09.529 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Grid connection closed
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 3:57:21 PM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 3:57:21 PM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 3:57:21 PM
Parsing thermostat data - key: sys_wifi_strength, value: -55 db
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Exception in thread "main" java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
        at io.homeassistant.devi.mqtt.service.DiscoveryService.Discover(DiscoveryService.java:244)
        at io.homeassistant.devi.mqtt.service.DiscoveryService.main(DiscoveryService.java:41)
```

**Comment by igor-podpalchenko** [comment]
Try the new release v1.0.7.
I don't have multiple devices for testing, so it's blind coding.
Please write a comment about whether it solved your problem.
Thanks.

**Comment by bob-tm** [comment]
Works! 
Дякую!

```
To configure thermostat's access. Download / open Devi application.
Go to settings -> Share Home -> OTP code will be generated. Enter this code, when requested.
For some reasons, first OTP code usually fails. Click back in mobile app and enter new code.
Try entering OTP few times.
Enter username (press Enter to use default [ha-user]): ha
20:41:51.900 [main] INFO  i.h.b.d.i.GridConnectionKeeper - Successfully connected to Danfoss grid
Home data, userName: ha
Discovery cycle started
20:42:05.731 [main] INFO  i.h.b.d.i.GridConnectionKeeper - Last user is gone, disconnecting from Danfoss grid
20:42:05.734 [main] INFO  i.h.b.d.i.GridConnectionKeeper - Grid connection closed
20:42:05.747 [main] INFO  i.h.d.mqtt.service.DiscoveryService - Received DeviSmart thing: 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67 С/у
20:42:05.751 [main] INFO  i.h.d.mqtt.service.DiscoveryService - Received DeviSmart thing: 1dbd5d7d402ee334a8792b5bed13f10e8d6237a4f44d9afcac965ce3169f1b12 Баня
20:42:05.751 [main] INFO  i.h.d.mqtt.service.DiscoveryService - Received DeviSmart thing: 58ace24aa181f8252c8a6204e1a34bb7b13ccc998b8adb4693e075bab7b9696f Гараж
Discovery cycle ended
Querying thermostat serial numbers started
Connecting to peer: 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67
20:42:05.977 [pool-1-thread-1] INFO  i.h.b.d.i.GridConnectionKeeper - Successfully connected to Danfoss grid
20:42:05.980 [pool-1-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connecting to peer 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67
20:42:06.048 [pool-1-thread-1] WARN  i.h.b.d.internal.SDGPeerConnector - Device went offline: Connection refused by grid: 1
Connecting to peer: 1dbd5d7d402ee334a8792b5bed13f10e8d6237a4f44d9afcac965ce3169f1b12
20:42:08.796 [pool-2-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connecting to peer 1dbd5d7d402ee334a8792b5bed13f10e8d6237a4f44d9afcac965ce3169f1b12
20:42:09.514 [pool-2-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connection established
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_serial_number, value: 10005675
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_serial_number, value: 10005675
20:42:09.525 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Last user is gone, disconnecting from Danfoss grid
20:42:09.525 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Grid connection closed
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005675
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 4:44:03 PM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005675
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 4:44:03 PM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005675
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 4:44:03 PM
Parsing thermostat data - key: sys_wifi_strength, value: -51 db
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005675
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Connecting to peer: 58ace24aa181f8252c8a6204e1a34bb7b13ccc998b8adb4693e075bab7b9696f
20:42:12.061 [pool-3-thread-1] INFO  i.h.b.d.i.GridConnectionKeeper - Successfully connected to Danfoss grid
20:42:12.063 [pool-3-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connecting to peer 58ace24aa181f8252c8a6204e1a34bb7b13ccc998b8adb4693e075bab7b9696f
20:42:13.160 [pool-3-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connection established
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_serial_number, value: 10005889
20:42:13.162 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Last user is gone, disconnecting from Danfoss grid
20:42:13.163 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Grid connection closed
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_serial_number, value: 10005889
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005889
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 9:12:36 AM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005889
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 9:12:36 AM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005889
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 9:12:36 AM
Parsing thermostat data - key: sys_wifi_strength, value: -61 db
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10005889
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Awaiting query completion
20:42:16.297 [pool-1-thread-1] INFO  i.h.b.d.i.GridConnectionKeeper - Successfully connected to Danfoss grid
20:42:16.298 [pool-1-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connecting to peer 7a0a50464dfd8c418587626773791a00f7abef819037c8626e74eaf094a11b67
20:42:17.980 [pool-1-thread-1] INFO  i.h.b.d.internal.SDGPeerConnector - Connection established
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_serial_number, value: 10006152
20:42:17.981 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Last user is gone, disconnecting from Danfoss grid
20:42:17.982 [SDG socket thread.1] INFO  i.h.b.d.i.GridConnectionKeeper - Grid connection closed
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 3:57:21 PM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 3:57:21 PM
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Parsing thermostat data - key: sys_production_date, value: Aug 12, 2016, 3:57:21 PM
Parsing thermostat data - key: sys_wifi_strength, value: -51 db
Parsing thermostat data - key: sys_connection_count, value: 3
Parsing thermostat data - key: sys_hardware_version, value: 3.1
Parsing thermostat data - key: sys_firmware_version, value: 1.0.127
Parsing thermostat data - key: sys_serial_number, value: 10006152
Parsing thermostat data - key: sys_wifi_connect_ssid, value: /dev/null
Configuration complete. devi_config.json is generated
```

**Comment by igor-podpalchenko** [comment]
Будь ласка! :)
